// Fictional roster — no real-brand names.
window.CARS = [
  {
    id: 'aether',
    name: 'Aether GT-X',
    maker: 'Vansten Motorworks',
    class: 'Hypercar',
    year: 2027,
    tagline: 'A blueprint torn from a wind tunnel.',
    bio: 'Twin-stack hybrid V12. Active aero that breathes. Built for cathedral straights and night-pour rain.',
    accent: '#34D7FF',
    accent2: '#7C5CFF',
    bg: 'radial-gradient(ellipse at 50% 60%, #0a2a4d 0%, #050913 60%, #02040a 100%)',
    sceneLabel: 'COASTAL HIGHWAY · 02:14 AM',
    stats: { top: 287, speed: 96, handling: 88, accel: 94, launch: 91, brake: 89 },
    powertrain: '6.2L V12 Hybrid · 1,184 hp',
    drivetrain: 'AWD',
    weight: '1,420 kg',
    zero: '2.1s',
    model3d: true,
  },
  {
    id: 'vortex',
    name: 'Vortex R9 Stripeback',
    maker: 'Cordell Performance',
    class: 'Muscle',
    year: 2026,
    tagline: 'Loud on purpose.',
    bio: 'Naturally-aspirated 8.1, carbon driveshaft, deletes for days. Wakes up the whole valley.',
    accent: '#FF7A1A',
    accent2: '#FFD23A',
    bg: 'radial-gradient(ellipse at 50% 65%, #4a1b04 0%, #1b0a02 60%, #0a0301 100%)',
    sceneLabel: 'DESERT MILE · 17:42',
    stats: { top: 244, speed: 88, handling: 71, accel: 92, launch: 96, brake: 74 },
    powertrain: '8.1L V8 · 798 hp',
    drivetrain: 'RWD',
    weight: '1,690 kg',
    zero: '2.7s',
  },
  {
    id: 'nimbus',
    name: 'Nimbus Spectre',
    maker: 'Hayashi Tuning Lab',
    class: 'Drift / Tuner',
    year: 2025,
    tagline: 'Sideways, on purpose, always.',
    bio: 'Triple-rotor screamer. Hydraulic e-brake. Built in a Yokohama lockup over six monsoons.',
    accent: '#FF3DA5',
    accent2: '#A45CFF',
    bg: 'radial-gradient(ellipse at 50% 60%, #3a0a3c 0%, #160520 60%, #07020c 100%)',
    sceneLabel: 'NEON DOCKS · 23:58',
    stats: { top: 261, speed: 84, handling: 97, accel: 86, launch: 79, brake: 88 },
    powertrain: '2.6L Triple-Rotor · 612 hp',
    drivetrain: 'RWD',
    weight: '1,180 kg',
    zero: '3.0s',
  },
  {
    id: 'solstice',
    name: 'Solstice Apex',
    maker: 'Hjalmar Rallisport',
    class: 'Rally',
    year: 2026,
    tagline: 'Eats gravel for breakfast.',
    bio: 'Flat-four anti-lag, hydraulic handbrake, raid suspension. Born for liaison stages in the rain.',
    accent: '#A4F03A',
    accent2: '#3AF0C7',
    bg: 'radial-gradient(ellipse at 50% 60%, #0a3a1a 0%, #051a10 60%, #02080a 100%)',
    sceneLabel: 'ALPINE SS6 · 08:11',
    stats: { top: 232, speed: 79, handling: 94, accel: 88, launch: 92, brake: 86 },
    powertrain: '2.4L Flat-4 Turbo · 540 hp',
    drivetrain: 'AWD',
    weight: '1,310 kg',
    zero: '2.9s',
  },
  {
    id: 'onyx',
    name: 'Onyx Phantom',
    maker: 'Maison Velin',
    class: 'Grand Tourer',
    year: 2027,
    tagline: 'Quiet money.',
    bio: 'Hand-rolled aluminium. Twin-turbo W16. Crosses a country before its coffee gets cold.',
    accent: '#F0F2F5',
    accent2: '#9AA3B2',
    bg: 'radial-gradient(ellipse at 50% 60%, #1a1d24 0%, #0a0c10 60%, #030406 100%)',
    sceneLabel: 'PRIVATE AERODROME · 05:30',
    stats: { top: 304, speed: 99, handling: 82, accel: 89, launch: 84, brake: 91 },
    powertrain: '8.0L W16 Quad-Turbo · 1,420 hp',
    drivetrain: 'AWD',
    weight: '1,910 kg',
    zero: '2.3s',
  },
];
